### ISSUE TITLE
Passing params to xgboost

### ISSUE THREAD

**Issue by dashaub** [ellisp/forecastxgb-r-package#18]
It appears passing `param` arguments to `xgboost()` and `xgb.train()` don't have any impact. For example, 
```
> library(forecastxgb)
> set.seed(3)
> a <- xgbts(AirPassengers, params = list(eta = .0001))
Stopping. Best iteration: 64
> 
> set.seed(3)
> a <- xgbts(AirPassengers)
Stopping. Best iteration: 64
```
Any ideas what's going on here?

**Comment by ellisp** [comment]
the ... were going through to xgboost for the final model fitting, but not to the cross-validation stage.  It should be fixed now.
