### ISSUE TITLE
Bug - cannot handle non-integer frequency

### ISSUE THREAD

**Issue by SpencerDH** [ellisp/forecastxgb-r-package#29]
# xgbar.R appears to assign incorrect number of rows to matrix x for some values of maxlag

The following line of code:
`x[ , maxlag + 1] <- time(y2)`
returns this error message:
`Error in x[, maxlag + 1] <- time(y2) : 
  number of items to replace is not a multiple of replacement length`

It appears that the error is caused by x and y2 having inconsistent lengths from R's handling of indexing with decimals, in the event that (as seems to usually be the case) maxlag is a floating point number.

Consider the outcome if maxlag = 54.75 and orign = 120:

`n <- orign - maxlag
  y2 <- ts(origy[-(1:(maxlag))], start = time(origy)[maxlag + 1], frequency = f)`

n will be 120 - 54.75 = 65.25. In determining the length of y2 with the decimal indexing of maxlag, R rounds the index of 54.75 down to 54, which causes y2 to be of length 120 - 54 = 66.

However, when the matrix x is created, n = 65.25 is used for the number of rows. R rounds this number down to the nearest integer less than this value, 65, which creates a matrix with 65 rows:

`ncolx <- ifelse(seas_method == "dummies", maxlag + f, maxlag + 1)
  x <- matrix(0, nrow = n, ncol = ncolx)`

Thus, y2 is of length 66, and x has 65 rows, which causes a "number of items to replace is not a multiple of replacement length" error when this line is run:

`x[ , maxlag + 1] <- time(y2)`

**Comment by ellisp** [comment]
i only considered `maxlag` ever being an integer so my first instinct with this was to force it to be one (round it or possibly stop).  What would the use case be for having a non-integer maxlag? (I obviously have just not thought of something).

**Comment by SpencerDH** [comment]
In my case, it came up because the frequency of the time series is a floating point number (52.25 for number of weeks in a year over the course of several years, with the 0.25 accounting for leap years). I'm not sure how common using a non-integer frequency is, though.
