### ISSUE TITLE
the meaning of the model reults

### ISSUE THREAD

**Issue by xiaoye10** [ellisp/forecastxgb-r-package#34]
library(forecastxgb)
model <- xgbar(gas)
model$y
model$y2
model$x
model$model
model$fitted
model$maxlag
model$seas_method
model$diffs
model$lambda
model$method
library(fpp)
consumption <- usconsumption[ ,1]
income <- matrix(usconsumption[ ,2], dimnames = list(NULL, "Income"))
consumption_model <- xgbar(y = consumption, xreg = income)
consumption_model$origxreg
consumption_model$ncolxreg
     Can you explain the model$y、model$y2、model$x、model$model、model$fitted、model$maxlag、model$seas_method、model$diffs、model$lambda model$method、consumption_model$origxreg、consumption_model$ncolxreg?  Thank you

**Comment by ellisp** [comment]
I'll improve the documentation.  But for now, most of these should be not too difficult to guess.  Some of them eg maxlag, seas_method, lambda, y just return the arguments that were first provided to the function in the first place.  Others are intermediate transformations of the data.

Any particular one that is puzzling you?

**Comment by ellisp** [comment]
If you reinstall from GitHub now, the helpfile for `?xgbar` is more comprehensive.  Could you let me know if it helps?
